version: '3.3'

services:
  redis:
    image: redis:latest
    container_name: redis
    volumes:
    - ./redis_data:/data
    networks:
    - backend
    ports:
    - "6379:6379"
    restart: always
networks:
  backend:
    driver: bridge