version: '3.3'

services:
  tomcat:
    image: tomcat:9.0.8-jre8
    container_name: tomcat
    volumes:
      - ./target/:/usr/local/tomcat/webapps/
    networks:
      - backend
    ports:
      - "8080:8080"
    restart: always
networks:
  backend:
    driver: bridge